import { Router } from 'express';
import { config } from '../config/index.js';

const router = Router();
const MAX_CHAT_TURNS = 8;
const MAX_MESSAGE_CHARS = 500;
const MAX_BRIEFING_CHARS = 4000;
const GROQ_NEWS_SYSTEM_PROMPT = `You are the assistant inside a news app. You will be given:
1) A "NEWS_BRIEFING" generated by another model (Nemotron). Treat it as the only trusted context.
2) A user question.

Your job:
- Answer using ONLY the information in NEWS_BRIEFING.
- If the answer is not in NEWS_BRIEFING, say: "I don’t have enough information in the current news briefing to answer that."
  Then ask 1 short follow-up question OR suggest what info to fetch (topic, country, timeframe).
- Be concise and factual. No made-up details. No guessing.
- If multiple items in the briefing are relevant, compare them clearly.
- If the user asks for “latest” or “today” and NEWS_BRIEFING does not specify recency, say you can’t confirm recency from the briefing.
- When possible, cite the briefing item number(s) like [1], [3] to show where you got it.

Output format:
- Start with a direct answer (2–6 sentences).
- Then (optional) a bullet list of supporting points with citations [#].
- If not answerable, use the required fallback sentence and follow-up.`;

router.get('/groq/status', (req, res) => {
  const groq = req.app.locals.groq;

  res.json({
    configured: Boolean(config.groqApiKey && groq?.isAvailable),
    model: config.groqModel,
  });
});

router.post('/groq/chat', async (req, res) => {
  const groq = req.app.locals.groq;
  const { messages = [], newsBriefing = '' } = req.body || {};

  if (!Array.isArray(messages) || messages.length === 0) {
    return res.status(400).json({ error: '"messages" must be a non-empty array.' });
  }

  if (!config.groqApiKey || !groq?.isAvailable) {
    return res.status(503).json({ error: 'API key not configured. Add GROQ_API_KEY to enable chat.' });
  }

  try {
    const reply = await groq.chatCompletion(normaliseMessages(messages, newsBriefing), {
      temperature: 0.6,
      maxTokens: config.defaults.groqMaxOutputTokens,
      topP: 0.9,
    });

    return res.json({ reply });
  } catch (err) {
    console.error('[GroqRoute] Chat error:', err.message);
    return res.status(500).json({ error: err.message });
  }
});

export default router;

function normaliseMessages(messages, newsBriefing) {
  const briefing = String(newsBriefing || 'No current news briefing is available.').slice(0, MAX_BRIEFING_CHARS);
  const cleaned = messages
    .filter((message) => typeof message?.content === 'string' && typeof message?.role === 'string')
    .map((message) => ({
      role: message.role,
      content: message.content.trim().slice(0, MAX_MESSAGE_CHARS),
    }))
    .filter((message) => message.content.length > 0);

  const conversation = cleaned
    .filter((message) => message.role !== 'system')
    .slice(-MAX_CHAT_TURNS)
    .map((message) => (
      message.role === 'user'
        ? {
            role: 'user',
            content: `NEWS_BRIEFING:\n${briefing}\n\nUSER QUESTION:\n${message.content}`,
          }
        : message
    ));

  return [
    { role: 'system', content: GROQ_NEWS_SYSTEM_PROMPT },
    ...conversation,
  ];
}
